# Generated by Django 4.0.4 on 2022-04-28 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='link',
            new_name='url',
        ),
        migrations.AddField(
            model_name='project',
            name='github_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
