# Generated by Django 4.0.4 on 2022-04-28 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_link_project_url_project_github_url'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
